# Generated by Django 4.0.5 on 2022-08-20 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام ')),
                ('family', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('education', models.CharField(max_length=50, verbose_name='تحصیلات ')),
                ('job_title', models.CharField(max_length=100, verbose_name='عنوان شغلی ')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('slug', models.SlugField(max_length=30)),
                ('mobile', models.IntegerField(verbose_name='موبایل')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_article', models.CharField(max_length=50, verbose_name='عنوان گروه ')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروه مقالات',
            },
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_article', models.CharField(max_length=50, verbose_name='نام مقاله')),
                ('image', models.ImageField(upload_to='image/blog', verbose_name='عکس اصلی')),
                ('abstract', models.CharField(max_length=200, verbose_name='خلاصه متن')),
                ('text_little', models.TextField(max_length=500, verbose_name='متن چکیده مقاله')),
                ('key_words', models.CharField(max_length=100, verbose_name=' کلمات کلیدی')),
                ('pdf_name', models.CharField(max_length=100, verbose_name=' نام فایل ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشتن مقاله ')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='  تاریخ انتشار ')),
                ('regester', models.DateTimeField(auto_now=True, verbose_name='  تاریخ بروز رسانی ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
                ('view', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('Author', models.ManyToManyField(to='blog.author', verbose_name='نویسنده')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.group', verbose_name='گروه مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'managed': True,
            },
        ),
    ]
