# Generated by Django 4.0.5 on 2022-08-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True, 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
