# Generated by Django 4.0.5 on 2022-08-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mobile',
            field=models.CharField(max_length=30, verbose_name='موبایل'),
        ),
    ]
