# Generated by Django 4.0.5 on 2022-08-17 10:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50, verbose_name='نام مکان')),
                ('info', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='image/places/', verbose_name='تصویر')),
                ('visit_day', models.CharField(max_length=60, verbose_name='روز بازدید')),
                ('visit_hour', models.CharField(max_length=60, verbose_name='ساعت بازدید')),
                ('rules', models.TextField(verbose_name=' قوانین و مقررات')),
                ('regeste', models.DateField(default=datetime.datetime(2022, 8, 17, 10, 26, 58, 549281, tzinfo=utc), verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان ها',
                'db_table': 'place_db',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='visitor_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'بازدید کننده',
                'verbose_name_plural': ' بازدید کنندگان',
                'db_table': 'visitor_db',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ticketprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='بهای بلیط')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.places', verbose_name='نام مکان')),
                ('visitor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.visitor_group', verbose_name='نوع بازدید کننده')),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
                'db_table': 'ticket_db',
                'managed': True,
            },
        ),
    ]
