# Generated by Django 4.0.5 on 2022-08-20 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name=' ایمیل')),
                ('subject', models.CharField(max_length=200, verbose_name=' عنوان پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_seen', models.BooleanField(default=False, verbose_name='وضعیت مشاهده توسط مدیر')),
                ('regedter', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'db_table': 'message_db',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='places',
            name='regeste',
            field=models.DateField(default=datetime.datetime(2022, 8, 20, 8, 45, 9, 170655, tzinfo=utc), verbose_name='تاریخ ثبت'),
        ),
    ]
