# Generated by Django 4.0.5 on 2022-08-20 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_mesaage_alter_places_regeste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesaage',
            old_name='regedter',
            new_name='regester',
        ),
        migrations.AlterField(
            model_name='places',
            name='regeste',
            field=models.DateField(default=datetime.datetime(2022, 8, 20, 8, 54, 29, 844916, tzinfo=utc), verbose_name='تاریخ ثبت'),
        ),
    ]
