# Generated by Django 4.0.5 on 2022-08-20 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_mesaage_options_alter_places_regeste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='regeste',
        ),
        migrations.AddField(
            model_name='places',
            name='regester',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
        ),
    ]
