# Generated by Django 4.0.5 on 2022-08-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام ')),
                ('family', models.CharField(max_length=100, verbose_name=' نام خانوادگی ')),
                ('password', models.IntegerField(verbose_name='پسورد')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'managed': True,
            },
        ),
    ]
